### Week 6 Numpy Practice Problems (continued)

In [1]:
import numpy as np

### Problem 1 (revisit)
Use numpy to create a function that adds a border filled with zeros around an existing array.

*Hint*: Use numpy's `pad` function. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html

Note: we did not cover this function in class, see if you are comfortable of reading numpy documents and learn on your own!

In [2]:
def add_border(x):
    return np.pad(x, 1, 'constant', constant_values=0)

In [3]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
assert claimed.shape == correct.shape
assert np.all(np.abs(claimed - correct) < 1e-8)

In [6]:
# Let's go throught the document together
# The np.pad function in NumPy is versatile and can be used in various ways to add borders or padding to arrays
# 1) Number of values padded to the edges of each axis. ((before_1, after_1), ... (before_N, after_N)) 
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='constant', constant_values=0)
print(padded)

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 0 3 4 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
# Pad with different mode 'constant' -> 'mode'
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='edge')
print(padded)

[[1 1 1 2 2]
 [1 1 1 2 2]
 [3 3 3 4 4]
 [3 3 3 4 4]
 [3 3 3 4 4]]


In [8]:
# Pad with different values on each side
x = np.array([[1, 2], [3, 4]])
padded = np.pad(x, pad_width=((1,2), (2,1)), mode='constant', constant_values=((5,6), (7,8)))
print(padded)

[[7 7 5 5 8]
 [7 7 1 2 8]
 [7 7 3 4 8]
 [7 7 6 6 8]
 [7 7 6 6 8]]


### Problem 2
Your task is to create a 2D array that shows the temperature for each city for each day of the week, assuming all cities have the same temperature pattern but with different baselines:

City 1: (first in the list): Use the temperatures as they are

City 2: Add  `5°C` to the temperatures

City 3: Subtract  `2°C` from the temperatures

In [9]:
def create_city_temperatures(temperatures, cities, offsets=None):
    if not offsets:
        offsets = [0, 5, -2]
    results = np.zeros((len(cities), len(temperatures)))
    for i, offset in enumerate(offsets):
        results[i] = temperatures + offset
    return results

In [28]:
def create_city_temperatures(temperatures, cities, offsets=None):
    if not offsets:
        offsets = np.array([0, 5, -2])
    return np.array([temperatures] * len(cities)) + offsets[:,np.newaxis]

In [29]:
# Given data
temperatures = np.array([20, 22, 25, 19, 23, 21, 18])  # 7 days
cities = np.array(['New York', 'Los Angeles', 'Chicago'])
# Create and print the result
result = create_city_temperatures(temperatures, cities)
print(result)
# Print with city names
for i, city in enumerate(cities):
    print(f"\n{city}:")
    print(result[i, :])

[[20 22 25 19 23 21 18]
 [25 27 30 24 28 26 23]
 [18 20 23 17 21 19 16]]

New York:
[20 22 25 19 23 21 18]

Los Angeles:
[25 27 30 24 28 26 23]

Chicago:
[18 20 23 17 21 19 16]
