### Week 5-2 NumPy Practice Problems

In [1]:
import numpy as np

### Warm up
NumPy creation and indexing.

In [3]:
# 1. Creates 3x3 array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# 2. Creates array [0, 2, 4, 6, 8]
np.array([0,2,4,6,8])

array([0, 2, 4, 6, 8])

In [6]:
# 3. 5 evenly spaced numbers from 0 to 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# Array indexing, Gets elements > 5
arr = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

arr[arr>5]

array([6, 7, 8, 9])

### Problem 1
Convert an array of Celsius measurements to Fahrenheit.
Note: `fahrenheit = (Celsius * 9/5) + 32`.

In [11]:
def convert_to_fahrenheit_list(temperatures):
    f_return = []
    for i in range(len(temperatures)):
        f_return.append(temperatures[i] * 9 / 5 + 32)
    return f_return

In [12]:
print("Testing with a regular list:")
temps_list = [0, 10, 20, 30]
print(convert_to_fahrenheit_list(temps_list))

Testing with a regular list:
[32.0, 50.0, 68.0, 86.0]


In [13]:
def convert_to_fahrenheit_numpy_array(temperatures):
    return temperatures * 9 / 5 + 32

In [14]:
print("\nTesting with a NumPy array:")
temps_array = np.array([0, 10, 20, 30])
print(convert_to_fahrenheit_numpy_array(temps_array))


Testing with a NumPy array:
[32. 50. 68. 86.]


### Problem 2
Use numpy to create a function that adds a border filled with zeros around an existing array.

*Hint*: Use numpy's `pad` function. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html

Note: we did not cover this function in class, see if you are comfortable of reading numpy documents and learn on your own!

In [15]:
def add_border(x):
    return np.pad(x, 1)

In [16]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
assert claimed.shape == correct.shape
assert np.all(np.abs(claimed - correct) < 1e-8)

### Problem 3
Create an $n \times n$ numpy array filled with a checkerboard pattern of zeros and ones. The first entry should be the integer `0`. Assume $n \ge 2$.

In [29]:
def make_checkerboard(n):
    return np.tile(np.array([[0, 1], [1, 0]]), (int(n/2), int(n/2)))

In [31]:
correct = \
    [[0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0]]
assert np.all(correct == make_checkerboard(8))

In [33]:
import numpy as np
x = np.arange(10)